language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls
    - pip install future
    - pip install six
script: sh bin/travis-run.sh
after_success:
    - coveralls
