# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(Agent.BuildDirectory)
    ls $(Agent.BuildDirectory)/s/
    # If the extension folder does not exist create it.
    if [ ! -d $(CKANEXTS_PATH)$(EXT_NAME) ]
    then
      echo Extension folder does not exist, creating it now.
      sudo mkdir $(ckanexts_path)$(ext_name)
    else
      echo Extension folder exists, clearing old contents!
      rm -r $(ckanexts_path)$(ext_name)/*
    fi
    echo Copying new files
    sudo cp $(Agent.BuildDirectory)/s/* $(ckanexts_path)$(ext_name)
  displayName: 'Run a multi-line script'
