# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: |

    echo Cloned repo into $(Agent.BuildDirectory)/s/
    echo Repo contents:
    ls $(Agent.BuildDirectory)/s/
    
    # If the extension folder does not exist create it.
    if [ ! -d $(CKANEXTS_PATH)$(EXT_NAME) ]
    then
      echo Extension folder does not exist, creating it now.
      sudo mkdir $(ckanexts_path)$(ext_name)
    else
      echo Extension folder exists, clearing old contents!
      rm -r $(ckanexts_path)$(ext_name)/*
    fi
    echo Copying new files
    sudo cp -r $(Agent.BuildDirectory)/s/* $(ckanexts_path)$(ext_name)
  displayName: 'Updating extension files'

- script: |
    sudo docker-compose -f $(docker_compose_path) down 
    echo skipping for now
  continueOnError: true
  displayName: 'Shutting down CKAN'

- script: |
    cd $(docker_path)
    sudo docker-compose up -d 
    echo skipping for now
  displayName: 'Restarting CKAN'  
  env:
    DATASTORE_READONLY_PASSWORD: $(datastore_readonly_password)
    POSTGRES_PASSWORD: $(postgres_password)
    


