name: remote_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the branch
  push:
    branches: [ actions_deploy ]
  pull_request:
    branches: [ actions_deploy ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              whoami
              cd ${{ secrets.ACTIONS_FOLDER }}
              ls -al
              ./git_update_vitality_prototype.sh
